export const cardData = [
    {
        name: 'Harry Potter',
        image: '',
        value: 1,
        clicked: false,
    },
    {
        name: 'Ron Weasley',
        image: '',
        value: 2,
        clicked: false,
    },
    {
        name: 'Hermione Granger',
        image: '',
        value: 3,
        clicked: false,
    },
    {
        name: 'Ginny Weasley',
        image: '',
        value: 4,
        clicked: false,
    },
    // {
    //     name: 'Fred Weasley',
    //     image: '',
    //     value: 5,
    //     clicked: false,
    // },
    // {
    //     name: 'George Weasley',
    //     image: '',
    //     value: 6,
    //     clicked: false,
    // },
    // {
    //     name: 'Neville Longbottom',
    //     image: '',
    //     value: 7,
    //     clicked: false,
    // },
    // {
    //     name: 'Luna Lovegood',
    //     image: '',
    //     value: 8,
    //     clicked: false,
    // },
    // {
    //     name: 'Cedric Diggory',
    //     image: '',
    //     value: 9,
    //     clicked: false,
    // },
    // {
    //     name: 'Dean Thomas',
    //     image: '',
    //     value: 10,
    //     clicked: false,
    // },
    // {
    //     name: 'Seamus Finnigan',
    //     image: '',
    //     value: 11,
    //     clicked: false,
    // },
    // {
    //     name: 'Cho Chang',
    //     image: '',
    //     value: 12,
    //     clicked: false,
    // },
    // {
    //     name: 'Lavender Brown',
    //     image: '',
    //     value: 13,
    //     clicked: false,
    // },
    // {
    //     name: 'Draco Malfoy',
    //     image: '',
    //     value: 14,
    //     clicked: false,
    // },
    // {
    //     name: 'Vincent Crabbe',
    //     image: '',
    //     value: 15,
    //     clicked: false,
    // },
    // {
    //     name: 'Gregory Goyle',
    //     image: '',
    //     value: 16,
    //     clicked: false,
    // },
]
